### ISSUE TITLE
Bad link pointing to GNU MCU OpenOCD release instead of GNU ARM OpenOCD

### ISSUE THREAD

**Issue by priyanka8929** [gnuarmeclipse/gnuarmeclipse.github.io-source#4]
There's a bad link on [this page](http://gnuarmeclipse.github.io/openocd/download/) which provides instructions to download GNU ARM OpenOCD. The GitHub releases link(shown in the screen shot below) points to GNU MCU OpenOCD release instead of GNU ARM OpenOCD which leads to downloading of wrong package if you don't verify the full name in the package.

![image](https://user-images.githubusercontent.com/5490319/27652177-b1a5a04c-5bef-11e7-8dd6-69b55b75d86b.png)

**Comment by priyanka8929** [comment]
#No fix needed, this was a mistake on my part.

**Comment by ilg-ul** [comment]
the project is currently rebranding to GNU MCU Eclipse.
